import I18n from "./i18n";
import Role from "./role";
import Tabs from "./tabs";
import Title from "./title";
import Video from "./video";
export { I18n as I, Role, Tabs, Title, Video };
export * from "./form";
export * from "./img";
export * from "./message";
export * from "./permission";
export * from "./table";
